### ISSUE TITLE
AWS::EC2::Volume.VolumeType causes panic

### ISSUE THREAD

**Issue by yeungda** [jagregory/cfval#26]
When I enter this template:
```
{                              
  "Resources": {               
    "Volume": {                
      "Type": "AWS::EC2::Volume",     
      "Properties": {          
        "VolumeType": "standard"        
      }
    }
  }
}
```
cfval shows this error:

```
panic: interface conversion: interface is string, not []interface {}

goroutine 1 [running]:
github.com/jagregory/cfval/schema.Schema.Validate(0x1, 0x0, 0x0, 0x0, 0x0, 0x7f84f932a210, 0xc820010310, 0x7f84f932a2b8, 0xc8200da0c0, 0x0, ...)
        /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/schema.go:63 +0x143
github.com/jagregory/cfval/schema.Properties.Validate(0xc8200da060, 0x7f84f932a980, 0xc820086bd0, 0x0, 0x0, 0x0, 0x90)
        /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/properties.go:41 +0xa95
github.com/jagregory/cfval/schema.Resource.Validate(0x69eb80, 0x10, 0x0, 0xc8200da060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/resource.go:18 +0xfa
github.com/jagregory/cfval/schema.resourceValidate(0xc82018f590, 0x10, 0xc820175b00, 0x0, 0x7f84f932a8e0, 0xc820086b40, 0xc820086b40, 0x0, 0x0, 0x0)
        /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/template.go:49 +0x284
github.com/jagregory/cfval/schema.TemplateValidate(0xc82018d5e0, 0x7f84f932a8b0, 0xc820175740, 0x7f84f932a8b0, 0x0, 0x0, 0x0)
        /home/vagrant/cfval/src/github.com/jagregory/cfval/schema/template.go:15 +0x3c0
main.ValidateCommand.Run(0xc82000a070, 0x0, 0x0, 0xc820173d40)
        /home/vagrant/golang/src/github.com/jagregory/cfval/main.go:174 +0x788
main.(*ValidateCommand).Run(0x7d3c58, 0xc82000a070, 0x0, 0x0, 0x6e2ff0)
        <autogenerated>:6 +0xab
github.com/mitchellh/cli.(*CLI).Run(0xc8200b83c0, 0xc820175830, 0x0, 0x0)
        /home/vagrant/cfval/src/github.com/mitchellh/cli/cli.go:153 +0x538
main.main()
        /home/vagrant/golang/src/github.com/jagregory/cfval/main.go:201 +0x181

goroutine 5 [runnable]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x37
```

Using version `dba9c5fc82c1dafbe858ad427872e113be8d013e` of `cfval`.

**Comment by jagregory** [comment]
Some improvements to the type validation have fixed the panic (yay), but highlighted the real issue:

    Resources.Volume.VolumeType ......... string used in List<EBS Block Device Volume Type> Array property

aka. The property was setup wrong in the definition, incorrectly marked as an array. Oops. Fixed in 0b2121c.
