### ISSUE TITLE
GetAtt GroupId of SecurityGroup causes panic

### ISSUE THREAD

**Issue by yeungda** [jagregory/cfval#29]
When I validate this template:

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "sg": {
      "Type": "AWS::EC2::SecurityGroup",
      "Properties": {
      }
    },
    "elb": {
      "Type": "AWS::ElasticLoadBalancing::LoadBalancer",
      "Properties": {
        "SecurityGroups": [ { "Fn::GetAtt": [ "sg", "GroupId" ] } ]
      }
    }
  }
}
```
I get this error:
```
panic: interface conversion: interface is parse.IntrinsicFunction, not string

goroutine 1 [running]:
github.com/jagregory/cfval/schema.resourceID.Validate(0x696a30, 0xf, 0xc82003e580, 0x39, 0xc8200683c0, 0x64dc40, 0xc82018f8c0, 0x7ff5981caa68, 0xc820089320, 0x0, ...)
        /home/vagrant/golang/src/github.com/jagregory/cfval/schema/value_id.go:41 +0x19a
github.com/jagregory/cfval/schema.(*resourceID).Validate(0xc8200db200, 0x64dc40, 0xc82018f8c0, 0x7ff5981caa68, 0xc820089320, 0x0, 0x0, 0x0, 0x0, 0x0)
        <autogenerated>:90 +0xfa
github.com/jagregory/cfval/schema.validateValue(0x64dc40, 0xc82018f8c0, 0x7ff5981caa68, 0xc820089320, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vagrant/golang/src/github.com/jagregory/cfval/schema/schema.go:116 +0x11e
github.com/jagregory/cfval/schema.Schema.Validate(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ff5981c6350, 0xc8200db200, 0x0, 0x64dc40, ...)
        /home/vagrant/golang/src/github.com/jagregory/cfval/schema/schema.go:54 +0x197
github.com/jagregory/cfval/schema.validateArray(0x7ff5981c6350, 0xc8200db200, 0x5e6ce0, 0xc82018f8e0, 0x7ff5981caa68, 0xc820089200, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vagrant/golang/src/github.com/jagregory/cfval/schema/schema.go:67 +0x45d
github.com/jagregory/cfval/schema.Schema.Validate(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ff5981c6288, 0xc8200cb770, 0x0, 0x5e6ce0, ...)
        /home/vagrant/golang/src/github.com/jagregory/cfval/schema/schema.go:52 +0x136
github.com/jagregory/cfval/schema.Properties.Validate(0xc8200db260, 0x7ff5981ca9f8, 0xc820089050, 0x0, 0x0, 0x0, 0x90)
        /home/vagrant/golang/src/github.com/jagregory/cfval/schema/properties.go:41 +0xa95
github.com/jagregory/cfval/schema.Resource.Validate(0x6cc180, 0x27, 0xc8200db170, 0xc8200db260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vagrant/golang/src/github.com/jagregory/cfval/schema/resource.go:18 +0x119
github.com/jagregory/cfval/schema.resourceValidate(0xc8201e80f0, 0x27, 0xc8201e83f0, 0xc8201e9170, 0x7ff5981ca950, 0xc820088fc0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vagrant/golang/src/github.com/jagregory/cfval/schema/template.go:49 +0x293
github.com/jagregory/cfval/schema.TemplateValidate(0xc82018f5a0, 0x7ff5981ca920, 0xc820175770, 0xc8201e91a0, 0xc8201e91a0, 0x0, 0x0, 0x0)
        /home/vagrant/golang/src/github.com/jagregory/cfval/schema/template.go:15 +0x3db
main.ValidateCommand.Run(0xc82000a070, 0x0, 0x0, 0xc820173d40)
        /home/vagrant/golang/src/github.com/jagregory/cfval/main.go:180 +0x81b
main.(*ValidateCommand).Run(0x7f5d60, 0xc82000a070, 0x0, 0x0, 0x6ff3f8)
        <autogenerated>:6 +0xab
github.com/mitchellh/cli.(*CLI).Run(0xc8200bc3c0, 0xc820175860, 0x0, 0x0)
        /home/vagrant/golang/src/github.com/mitchellh/cli/cli.go:153 +0x538
main.main()
        /home/vagrant/golang/src/github.com/jagregory/cfval/main.go:207 +0x181

goroutine 5 [runnable]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x37
```
Using this version `a1b2fef9596d0677dff72479f5ce6de9047ee5ad`

**Comment by jagregory** [comment]
Should be fixed in ab95e40070307be0f0bce8f1a195530559dcf7fd.
